import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card } from '@/components/ui/card';
import MetricCards from '@/components/teacher/MetricCards';
import Insights from '@/components/teacher/Insights';
import StudentRow from '@/components/teacher/StudentRow';
import { ArrowLeft, Check, X, Plus, Loader2 } from 'lucide-react';

export default function TeacherDashboard() {
  const [user, setUser] = useState(null); const [classes, setClasses] = useState([]); const [members, setMembers] = useState([]); const [essays, setEssays] = useState([]); const [selected, setSelected] = useState(''); const [name, setName] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { const me = await base44.auth.me(); setUser(me); const [c, m, e] = await Promise.all([base44.entities.Classroom.filter({ teacher_id: me.id }, '-created_date'), base44.entities.ClassMembership.filter({ teacher_id: me.id }, '-created_date'), base44.entities.Essay.filter({ teacher_ids: me.id, status: 'completed' }, '-created_date', 200)]); setClasses(c); setMembers(m); setEssays(e); setSelected(s => s || c[0]?.id || ''); setLoading(false); };
  useEffect(() => { load(); }, []);
  const createClass = async (e) => { e.preventDefault(); const code = Math.random().toString(36).slice(2, 8).toUpperCase(); await base44.entities.Classroom.create({ name, code, teacher_id: user.id, teacher_name: user.full_name || user.email, school_id: user.school_id || '' }); setName(''); await load(); };
  const review = async (id, decision) => { await base44.functions.invoke('reviewClassJoin', { membershipId: id, decision }); await load(); };
  if (loading) return <div className="min-h-screen flex items-center justify-center"><Loader2 className="w-8 h-8 animate-spin" /></div>;
  if (user?.account_type !== 'teacher') return <div className="min-h-screen flex items-center justify-center"><Card className="p-6 text-center"><p className="mb-4">Este painel é exclusivo para professores.</p><Link to="/professor"><Button>Voltar</Button></Link></Card></div>;
  if (!user?.school_id) return <div className="min-h-screen flex items-center justify-center"><Card className="p-6 text-center"><p className="mb-2 font-semibold">Vínculo institucional necessário</p><p className="text-sm text-muted-foreground mb-4">Cadastre-se com o código fornecido pela escola para criar turmas.</p><Link to="/professor"><Button>Voltar</Button></Link></Card></div>;
  const currentClass = classes.find(c => c.id === selected); const approved = members.filter(m => m.class_id === selected && m.status === 'approved'); const pending = members.filter(m => m.class_id === selected && m.status === 'pending'); const studentIds = approved.map(m => m.student_id); const classEssays = essays.filter(e => studentIds.includes(e.created_by_id));
  return <div className="min-h-screen bg-background text-foreground"><div className="max-w-5xl mx-auto px-4 pt-6"><h1 className="font-semibold">Painel do professor</h1><p className="text-sm text-muted-foreground">Acompanhe o desempenho das suas turmas</p></div><main className="max-w-5xl mx-auto p-4 py-6 space-y-6"><Card className="p-4"><form onSubmit={createClass} className="flex gap-2"><Input value={name} onChange={e => setName(e.target.value)} placeholder="Nome da nova turma" aria-label="Nome da nova turma" required /><Button><Plus className="w-4 h-4 mr-2" />Criar turma</Button></form></Card>{classes.length ? <><div className="flex gap-2 overflow-x-auto pb-1">{classes.map(c => <Button key={c.id} variant={selected === c.id ? 'default' : 'outline'} onClick={() => setSelected(c.id)}>{c.name}</Button>)}</div><Card className="p-4 flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{currentClass?.name}</p><p className="text-sm text-muted-foreground">Código para alunos</p></div><code className="text-lg font-bold tracking-widest bg-muted px-3 py-2 rounded">{currentClass?.code}</code></Card>{pending.length > 0 && <Card className="p-4"><h2 className="font-semibold mb-3">Solicitações pendentes</h2><div className="space-y-2">{pending.map(m => <div key={m.id} className="flex items-center gap-3 border rounded-lg p-3"><div className="flex-1 min-w-0"><p className="font-medium truncate">{m.student_name}</p><p className="text-sm text-muted-foreground truncate">{m.student_email}</p></div><Button size="icon" variant="outline" aria-label="Recusar" onClick={() => review(m.id, 'rejected')}><X className="w-4 h-4" /></Button><Button size="icon" aria-label="Aprovar" onClick={() => review(m.id, 'approved')}><Check className="w-4 h-4" /></Button></div>)}</div></Card>}<MetricCards students={approved} essays={classEssays} /><Insights essays={classEssays} /><section><h2 className="font-semibold mb-3">Alunos da turma</h2><div className="space-y-2">{approved.map(m => <StudentRow key={m.id} membership={m} essays={classEssays.filter(e => e.created_by_id === m.student_id)} />)}{!approved.length && <p className="text-sm text-muted-foreground">Nenhum aluno aprovado nesta turma.</p>}</div></section></> : <Card className="p-8 text-center"><p className="text-muted-foreground">Crie sua primeira turma para começar.</p></Card>}</main></div>;
}